### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tfry-git** [nalimilan/R2HTML#6]
Hi @nalimilan ,

I merged a PR the other day, and added a small fix myself just now. Could you perhaps upload a new version?

Thanks!
Thomas

**Comment by nalimilan** [comment]
Sure, I've just done so. Would you be interested in becoming the maintainer BTW?

**Comment by tfry-git** [comment]
Thanks.

"Interested" is the wrong word, but it you were determined to drop maintainer status, I'd be willing to pick it up (and hoping to find the opportunity to pass it on, one day).

**Comment by nalimilan** [comment]
OK.  Given we only make a release very few years, I can continue doing it!

**Comment by nalimilan** [comment]
It's on CRAN!
